//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Original { get; set; }
        public string ISBN { get; set; }
        public string Describe { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
