//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EShopDB : DbContext
    {
        public EShopDB()
            : base("name=EShopDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OtherType> OtherType { get; set; }
        public DbSet<BookType> BookType { get; set; }
        public DbSet<BookInfo> BookInfo { get; set; }
        public DbSet<BookSale> BookSale { get; set; }
        public DbSet<Recommend> Recommend { get; set; }
        public DbSet<SaleDetail> SaleDetail { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
