//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetailView
    {
        public string Id { get; set; }
        public string BsId { get; set; }
        public string SaleNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string BookId { get; set; }
        public string BookName { get; set; }
        public string BookISBN { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public Nullable<int> BookNum { get; set; }
    }
}
